---
title: Marco
timezone: UTC
collections:
  agen:
    title: Agen
    output: true
  cabang:
    title: Cabang
    output: true
  hotel:
    title: Hotel
    output: true
  paket:
    title: Paket
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: MARCO Haji, Umrah
description: Muslim Trip Tour & Travel
avatar: 
wa: 6285204023000
footer-links: 
disqus: 
google_analytics: UA-77777148-3
url: http://marcoumrah.com
baseurl: ''
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
