---
title: Marco
timezone: UTC
collections:
  agen:
    title: Agen
    output: true
  cabang:
    title: Cabang
    output: true
  gallery:
    title: Gallery
    output: true
  hotel:
    title: Hotel
    output: true
  paket:
    title: Paket
    output: true
  posts:
    title: Posts
    output: true
  testimonials:
    title: Testimonials
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: paket
  values:
    layout: paket
    image:
    - "/uploads/hotel-al-fajar-1.jpg"
    - "/uploads/hotel-al-fajar-1.jpg"
    - "/uploads/hotel-al-fajar-1.jpg"
    maskapai: Saudi Airlines
    harga: 0
    hargasale: 0
    hargausd: 0
    hargausdsale: 0
    hotel:
    - Al Rawda Al Aqeeq
    durasi: 9
    paxroom: 4
- scope:
    path: ''
    type: hotel
  values:
    layout: blank
    image:
    - "/uploads/hotel-al-fajar-1.jpg"
    - "/uploads/hotel-al-fajar-1.jpg"
    - "/uploads/hotel-al-fajar-1.jpg"
    bintang: 5
    kota: Madinah
- scope:
    path: ''
    type: agen
  values:
    layout: blank
    agenwa: '0812xxxxxxxxx'
    agenalamat: Jl. xxxxxx
- scope:
    path: ''
    type: cabang
  values:
    layout: blank
    cabangwa: '0812xxxxxxxxx'
    cabangpic: Bpk / Ibu xxx
    cabangalamat: Jl. xxxxxx
    cabangtelp: "(02x) xxxx xxxx"
- scope:
    path: ''
    type: testimonials
  values:
    layout: blank
    image: "/masukkan-photo-jamaah.jpg"
name: MARCO UMRAH & HAJJ
description: Muslim Trip Tour & Travel
avatar: 
wa: 6281381462334
footer-links: 
disqus: 
google_analytics: UA-77777148-3
url: http://marcoumrah.com
baseurl: 
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
